name: Test

on:
  push:
    branches: [master, workflow]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}

      - uses: actions/setup-node@v2
        with:
          node-version: '^16'

      - name: npm install
        env:
          CI: true
        run: |
          npm install
          npm ci

      - name: Build
        if: github.base_ref != 'master' && github.base_ref != 'staging'
        run: |
          export NODE_OPTIONS=--max_old_space_size=8192
          npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./public